export const FETCH_PENDING = 'FETCH_PENDING'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'

export const SET_QUERY = 'SET_QUERY'
export const SET_PAGINATION = 'SET_PAGINATION'